### PR TITLE
Add shell.ExecFileArgs

### PR DESCRIPTION
**Pull request by katcipis**
Not sure if this is a great idea, but I was needing to call nash scripts from Go code, and my scripts take command line args. Checking out the current code I was unable a way to do so, but I found out code on the main package that did it and basically moved it. Probably not on the best way possible. Please advise :-)

### CODE REVIEW

**Comment by katcipis** [comment]
I think I may have missed some testing opportunity :-), if the idea is cool I can commit to write some tests.

**Comment by vitorarins** [comment]
Looks like a good idea to me. But I am no expert. @katcipis maybe you can create an issue and give a use case for us, just to make it clear.

**Comment by katcipis** [comment]
@vitorarins basically:

```
somescript.sh param1 param2
```

And from Go code I can call:

```
shell.ExecFileArgs("somescript.sh", "param1", "param2")
```

Right now I copied code from the main package to be able to do that,
[here](https://github.com/NeowayLabs/klb/blob/fixTests/tests/lib/nash/nash.go#L26).

**Comment by tiago4orion** [comment]
> And current use of ExecFile without args would still work too, it seems better.

I prefer this way =) I just was dumb and forgot about script arguments :/

**Comment by katcipis** [comment]
@tiago4orion shut up, you remember to implement the whole language right ? ;-)

**Comment by vitorarins** [comment]
@katcipis great! LGTM.

**Comment by katcipis** [comment]
@tiago4orion @vitorarins what about it now ?

**Comment by tiago4orion** [comment]
LGTM!

;)

**Pull request merged**
