### PR TITLE
Fix Releaser script

### PR DESCRIPTION
**Pull request by vitorarins**
- Add CGO_ENABLED depending on the os; 
- Nashfmt'd the script (sorry).

### CODE REVIEW

**Comment by katcipis** [comment]
It worked fine here with Go 1.2 ...that is odd

**Comment by katcipis** [comment]
@vitorarins specially since it happened on the tip perhaps it was some instability...or some non-determinism on the test. I changed the CI to use only Go >= 1.12 (using some Go 1.12 stdlib stuff on other branches) and it worked fine =).

**Comment by vitorarins** [comment]
I've been removed from neowaylabs organization on Docker hub, so I can't check why the image is failing to build on docker cloud.
But I think we can merge this.

**Comment by katcipis** [comment]
Why the fuck  would we remove you ? ¬¬

You have been re-added. I just checked that the Go version in the image is pretty old (1.8)...it could be something that we are using that is newer than that. I think even better type inference is newer than 1.8.

**Comment by vitorarins** [comment]
Ok thanks :)

So actually the Dockerfile is based on the old build process.
We need to update it to use the install script or something.

**Pull request merged**
